### ISSUE TITLE
Questions #7 & 8

### ISSUE THREAD

**Issue by DeeMa17** [learn-co-curriculum/programming-univbasics-3-quiz#2]
Perhaps it's me, but it appears that something is wrong with this. I'll attach screenshots of the lesson where this was explained.

![Quiz Error 2](https://user-images.githubusercontent.com/27648466/61075758-f0842900-a3d7-11e9-84f3-832c36fa4b67.png)
![Quiz Error 1](https://user-images.githubusercontent.com/27648466/61075759-f0842900-a3d7-11e9-8c0a-7c425b17d464.png)

**Comment by sgharms** [comment]
@DeeMa17 You're right, there's some subtlety here that's really hard to express and communicate and be consistent with. We'll adjust to make these harmonious.
